### ISSUE TITLE
after job processing

### ISSUE THREAD

**Issue by shaileshsitestrokes** [dataclay/event-scripts#2]
Hello,

I want add event for after each job 
below command i am using for saving video into another location
node E:\shaileshpc_backup\rend_cli\concatenate.js --details $data_batch --outdir $out_dir --outname "finalrender.mov"

i want to save video after rendering into different different location 
is this possible to created video saved into desired location?

Please help me out this?

Thanks

**Comment by ariestav** [comment]
Yes, but I don't think the `concatenate.js` script is the way to do this.  That script is really for "stitching" different jobs together from a single batch.

If you are on windows, you can simple create a Windows batch script that does this in practically two lines of code.  Assume this file exists at `E:\TemplaterTools\moveoutput.bat`

```
move %1 %2
```

Then, you would use the following in the `After Job` field in the "Setup Shell Commands" dialog within the Templater Preferences:

```
E:\TemplaterTools\moveoutput.bat $out_file "Z:\Archive\"
```

`Z:\Archive` is where you want the assets to be saved.

Does this help?

**Comment by blakmarkit** [comment]
Feel free to respond here or send an email https://dataclay.com/contact-us/ if you need further assistance. I'm going to mark this as closed.
